### ISSUE TITLE
FreeBSD 10 netmap-libpcap configure errors tcpreplay 4.1.0

### ISSUE THREAD

**Issue by cwitter** [appneta/tcpreplay#184]
Running FreeBSD 10 p10 with Netmap Kernel and netmap-libpcap installed. Running configure one tcpreplay  4.1.0 errors out: 

checking for library containing nl_handle_alloc... no
checking for numa_available in -lnuma... no
checking for pthread_create in -lpthread... yes
checking for library containing pcap_get_pfring_id... no
checking for library containing pcap_close... no
configure: error: Unable to link libpcap in /usr/local

**Comment by fklassen** [comment]
Currently we do not support libpcap-netmap. Instead you should use `./configure --with-netmap` to compile netmap support directly into Tcpreplay.

Discussed with @luigirizzo. The current "native netmap" approach may result in better performance than moving to libpcap-netmap, so I am changing the status from `Bug` to `Enhancement`. Will look at it again in a future release.

**Comment by fklassen** [comment]
It appears that it does work. Tried it with FreeBSD10 p12. But I had to backdate to a Feb 10 2014 version of `netmap-libcap` in order to compile. Here is the git version c77ffc1b7374d7baa5a6fc0841eb0dd6a8e60fab

Also if `/dev/netmap` does not exist, you must [compile and install netmap](https://forums.freebsd.org/threads/freebsd-10-1-missing-dev-netmap.51562/).

I am closing this request, and instead asking users to compile with `netmap`. On FreeBSD you will see that it gets picked up automatically when you run `./configure`. That also happens on Linux if you install `netmap` into default directories. Otherwise you will have to use `./configure --with-netmap=<directory>`.
