### ISSUE TITLE
How to replay as accurate as possible ? or why getting "abstime is deprecated" ?

### ISSUE THREAD

**Issue by asafshakedverint** [appneta/tcpreplay#271]
Hi,

I'm trying to replay pcaps recorded accurately using tcpdump / netsniff-ng, using tcpreplay v4.1.2,
but I can tell from external trustworthy equipment, they weren't replayed accurately enough

I was following the timing tips here... http://tcpreplay.synfin.net/wiki/tcpreplay

"-T gtod" gave the same unsatisfying results as not using -T at all
"-T nano" gave poor results, as it stretched replay time by 7 whole seconds

& "-T abstime" which should have been most promising, gave "abstime is deprecated"...
I also tried it on OS X Yosemite & El Capitan versions & got the same message... why ?
(BTW, regularly using RHEL 7.2)

Please also notice...
- I got worse results adding the "-K" and/or "--pktlen" flags
- Building with Quick Tx & using it got worse results as well (just a shot in the dark)
- Rounding the number of packets in capture to exactly 70K, given average packets/sec is exactly 500, in order to theoretically stay only in micro-second resolution calculations, also didn't help

Is it possible to practically replay in nano-second resolution ?
What's currently the most accurate way to replay ?

Any assistance would be highly appreciated :)

Thanks,

Asaf.

**Comment by fklassen** [comment]
`-T abstime` uses a deprecated method, i.e. a clock API that is no longer available.

Are you using PCAPNG files? Regular PCAP files only have usec resolution clocks. What amount of error are you seeing?

**Comment by asafshakedverint** [comment]
Thanks for the advice regarding the format… I did not know that
I recorded again in nano-seconds supporting format, compared to previous recording with Wireshark & saw 3 more figures after the dot ☺

However results are still not good – It’s not a matter of errors, rather replay accuracy
I’m recording from external equipment, replaying recording to it & comparing – it shows differences all through

This is the last try I ran today…
[root@localhost tmp]# netsniff-ng -i eno2 -o testrec7.pcap -s -k1 -T 0xa1b23c4d -n 17500
Running! Hang up with ^C!

       17500  packets incoming (25 unread on exit)
       17525  packets passed filter
           0  packets failed filter (out of space)
      0.0000% packet droprate
         140  sec, 168986 usec in total


[root@localhost tmp]# tcpreplay -i eno3 testrec7.pcap
Actual: 17500 packets (35525000 bytes) sent in 140.00 seconds.
Rated: 253600.0 Bps, 2.02 Mbps, 124.95 pps
Flows: 1 flows, 0.00 fps, 17500 flow packets, 0 non-flow
Statistics for network device: eno3
        Successful packets:        17500
        Failed packets:            0
        Truncated packets:         0
        Retried packets (ENOBUFS): 0
        Retried packets (EAGAIN):  0


BTW, try with “-T nano” still gave less accurate results, also with nano-second resolution recording


Any idea how to replay more accurately ?


Thanks,

Asaf.

**Comment by fklassen** [comment]
I did more investigation.

Instructions in http://tcpreplay.synfin.net/wiki/tcpreplay are outdated. Note that as of version 4.0, the new website is http://tcpreplay.appneta.com.

Version 4.0 is a total rewrite. I found that in newer OS X versions, the default system clock was faster than any other clock, and 'abstime' was deprecated. Also the TX mechanism was slow, so I re-wrote it. 

In 4.0 and newer TX timing is based on a tight loop that sleeps between packets. This reduced jitter from milliseconds to microseconds. Accuracy is driven by how fast a sleep op is. Usually that is about 2 microseconds on fast systems.

I wasn't familiar netsniff-ng so I did some digging and I found this https://github.com/netsniff-ng/netsniff-ng/blob/master/staging/time.c#L65. It is timestamping the packets in user context. That appears to be a design flaw. Although zero copy `mmap()` allows very fast copy of packets into userland, any advantage gained would be lost by doing timestamping in user mode. That is hundreds of times slower than doing timestamping in kernel mode.

My recommendation is to capture with `tcpdump` on a modern Linux system with a newer version of libpcap. As of libpcap 1.0.0, mmap is supported, but timestamping is done in the kernel. I think you will find it much more accurate. Also, if you use a large "-B" buffer option, you can generally capture at wire rates, although you may lose some timestamp accuracy.

Or better yet, do what I do. I use AppNeta appliances and capture with PathView. Our appliances timestamp at the NIC adapter, which on 10GigE is +- 30 nanosecond accuracy.

So, I'll ask the question again. What amount of error are you seeing? If you see more than a few microseconds or more error, your issue isn't in Tcpreplay. The problem is your software-based packet capture.

**Comment by asafshakedverint** [comment]
Thanks for tcpreplay “under the hood” ☺ indeed seems it shouldn’t be & probably not the cause of my issue

Regarding netsniff-ng, I got very good results capturing high bandwidth with it without packet loss
I’m no developer, but this flag “-N|--no-hwtimestamp  Disable hardware time stamping” suggests default is NIC/kernel timestamp, not ?
https://github.com/netsniff-ng/netsniff-ng/blob/master/tstamping.c

I am indeed capturing on modern RHEL 7.2 & I upgraded tcpdump + libcap versions to last stable, but unfortunately getting same results

I will surely suggest PathView in my organization as possible solution

The cause & amount of error are still under investigation… I will report if results are interesting to learn from ☺

Thanks again for all your help & good advice

Asaf.

**Comment by fklassen** [comment]
Hardware timestamping is fast, but  not accurate. It is only supported on i350 and i210 GigE adapters, an x550 10GigE adapters. On others, it timestamps in user mode, at least from what I can see. I suspect that modern tcpdump with a large "-B" will be faster when not using hardware timestamping.

**Comment by fklassen** [comment]
close as resolved

**Comment by ruben-TC** [comment]
This is still a problem.
I'm trying to playback video (ArtNet show), the bigger the show (more fixtures, more packets per frame) the bigger the time lag/drift, over 10min I already have a 1 min delay.
For a smaller show I have only a few seconds delay over 20min, but it's still unusable because it has to be synced to other effects specially sound, and it all works together.

It's a great tool but I can't use it for my use case.

`tcpreplay version: 4.5.2 (build git:v4.5.2)`

Edit: I had a similar problem in my early days of show electronics, I used a delay function in arduino and the small lags compounded over time, I then switched to read and compare the current milliseconds (as in comparing to the start of the sequence and not to the previous step) and it worked flawlessly. Maybe something similar could be implemented?

**Comment by lecourtb** [comment]
Hello. 
I made a small modification to **sleep.h** (gtod option) which considerably improves adherence to timings. 
This modification is perfect for my usage but is a bit dirty and cannot be taken as-is for commit. 
I send you the updated file (taken for master branch, commit **5bf1a6c**), in case you are interested. 
The idea is to maintain in variable **sleep_until** (it become static in my update, that what is dirty) the exact required date of the next packet to send. Thanks to that, there is no more sliding of timing (and no more resulting time dilatation of the replay).

[sleep.h.txt](https://github.com/user-attachments/files/28092206/sleep.h.txt)

**Comment by lecourtb** [comment]
Here are the results of the time accuracy before and after modification :
[tcpreplay.ods](https://github.com/user-attachments/files/28093115/tcpreplay.ods)
