### ISSUE TITLE
Option --fuzz corrupts packets

### ISSUE THREAD

**Issue by fklassen** [appneta/tcpreplay#333]
The attached capture was created with the test on OS X. Original file is `test.pcap`, which distributes with source code. 

Notice that the packet 15 has changed from an IP packet to an invalid Ethernet II.

Most likely this is because [this TODO](https://github.com/appneta/tcpreplay/blob/Feature_302_fuzz_option/src/tcpedit/fuzzing.c#L81) was never implemented.

[test.rewrite_l7fuzzing1.pcap](https://github.com/appneta/tcpreplay/files/852126/test.rewrite_l7fuzzing1.pcap.txt)

**Comment by fklassen** [comment]
@GabrielGanne can you comment on this? Is it expected that IP packets can be converted to something else?

I may be able to merge to Release_4.2 without this addressed.

**Comment by GabrielGanne** [comment]
Hi @fklassen ,

You are correct: fuzzing can indeed change any Byte, including ethertype.
I'm afraid I had forgotten this TODO ...

This is an idea I had which differs from what we would do at my work (dpi) : since most people do not care about code branches for many different protocols, editing the low-level protocol Bytes would result in dropping the packet instead of changing the course of the packet through the code.

Anyway, this TODO only requires parsing and skipping the first 3 layers, so I should be done quickly enough.
(or if you wish to close this release, I can do it for the next one)

Sorry about the trouble.

**Comment by fklassen** [comment]
@GabrielGanne, not a problem. My preference is to hold off 4.2 to get this feature in.  But if you don't have time to do this, I could release 4.2 (scheduled for Monday) and then release a 4.2.1 when you are ready.

As for updates, feel free to make a PR into my `Feature_302_fuzz_option` branch. Or easier still, just make a PR to my master branch. I found I can edit the PR and push to the branch of my choice.
