### ISSUE TITLE
Data loss during transmission using 'tcpreplay' at high speed and even with big pcap file

### ISSUE THREAD

**Issue by najamsaleem** [appneta/tcpreplay#615]
I Have 2 PCs connected to eachother. Combination is as follow

•	I am sending tcp pcap file between two PCs. Sender side is Debian and receiver side is Windows.

On sender side I am sending using ‘Tcpreplay’ and receiving it using ‘dumpcap’ on windows side. Both machines have 10 Gb cards. Systems has 16 GB of RAM, i7 8 Gen of CPU

I am facing these problems.

1)	For long file (around 45 Gb) even with ‘–t’ it is not reaching at 10Gb/s speed it reach max at 1.5 Gb/s in total. If I chop that file to (2 Gb size) and then send, it reaches at 5.5Gb/s speed.
I am confused by looking at this irregular behavior of tcpreplay. Why big file cannot reach max speed higher, whereas same small file reach speed higher than that.

2)	I checked a lot of different combinations of buffer (-B option of dumpcap), sending file type etc. on receiver side and I am seeing different losses on receiver side.

3)	Even I checked a lot more combinations, with big file it shows problem and error.

4)	When I used (-l loop ) option with tcpreplay I also notice loss, means increased file size increase loss.

I want to transfer the file at max speed possible with 0% data loss. This is my main priority. Help would be appreciated. Thanks

Some of the noticed statistics

45 Gb pcap with 45 million packets | using -t option |sender side throughput 1.5 Gb/s | Rx Buffer 1024 | Packets recieved 100% | Loss 0%

2 Gb (chopped) with 0.5 million packets | using -t option |sender side throughput 5.5 Gb/s | Rx Buffer 1024 | Packets recieved 100% | Loss 0%

2 Gb (chopped) with 0.5 million packets | using -t and -l 10 option |sender side throughput 5.5 Gb/s | Rx Buffer 1024 | Packets recieved 50% - 70% | Loss 50% - 30% (its not stable)

4 Gb (chopped) with 1 million packets | using -t option |sender side throughput 5.3 Gb/s | Rx Buffer 1024 | Packets recieved 55% - 70% | Loss 45% - 30% (its not stable)

**Comment by fklassen** [comment]
How are you measuring speed? Dumpcap and Windows are known to be quite slow. Better off reading interface stats, especially if you have a NIC on Linux side that can report successful sends (e.g. Mellanox). Better yet, send to a Linux box with modern kernel, with eBPF filter that simply drops packets and counts packets.

What exact command-line?

Also what version of Tcpreplay are you using?

Pro tip: fill out the bug template that pops up when you create an issue so that we can get more context around your issue.

**Comment by fklassen** [comment]
Also, another suggestion is adding [netmap](http://info.iet.unipi.it/~luigi/netmap/) support to the Linux side, however I am sure you will not see full wire rate because Windows usually cannot keep up. For an example of full 10G wire-rate Tcpreplay send/receive using Linux source/target see [the support website](http://tcpreplay.appneta.com/wiki/overview.html) which has examples and a video that will guide you.

Close for now as "not a bug"
